WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
COMMENT = _{ "#" ~ (!"\n" ~ ANY)* }
ident = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }
dunder_ident = @{ "__" ~ ASCII_ALPHA+ ~ "__"? }

term = _{
    paren_expression |
    function_call |
    MemberAccess |
    class_instantiation |
    number |
    string |
    ident
}

number = @{ int ~ ("." ~ ASCII_DIGIT*)? }
int = @{ "-"? ~ ASCII_DIGIT+ }
string = @{ "\"" ~ (!"\"" ~ ANY)* ~ "\"" }

MemberAccess = { ident ~ ("." ~ ident)+ | ident ~ "." ~ ident }

add = { "+" }
subtract = { "-" }
multiply = { "*" }
divide = { "/" }
eq = { "==" }
neq = { "!=" }
gt = { ">" }
lt = { "<" }
gte = { ">=" }
lte = { "<=" }

operator = _{
    add | subtract | multiply | divide |
    eq | neq | gt | lt | gte | lte |
    "and" | "or" | "not"
}

class_instantiation = { ident ~ "(" ~ term? ~ ")" ~ ";"}
function_call = { ident ~ "(" ~ ParramsList? ~ ")" ~ ";"}
ParramsList = { expression ~ ("," ~ expression)* }

expression = {
     (MemberAccess) ~ (operator ~ (MemberAccess | term))* |
     term ~ (operator ~ (MemberAccess | term))*
}

paren_expression = { "(" ~ expression ~ ")" }

binary_op = {   "+" | "-" | "*" | "/"   }
BinOperation = { (function_call | MemberAccess | term) ~ operator ~ expression }
KEYWORD_DEF = { "fn" }
KEYWORD_IF = { "if" }
KEYWORD_ELSE = { "else" }
KEYWORD_FOR = { "for" }
KEYWORD_WHILE = { "while" }
KEYWORD_CLASS = { "class" }

//
arg_list = { "(" ~ (ident ~ ("," ~ ident)*)? ~ ")" }

function_call_stmt = { (ident~"."~ function_call | function_call | class_instantiation) }
assignment_statement = { (MemberAccess | ident) ~ "=" ~ (term ~ ";" | function_call_stmt ) }
print_statement = { "print" ~ "(" ~ ParramsList ~ ")" ~ ";" }
return_statement = { "return" ~  expression ~ ";" }



if_statement = { KEYWORD_IF ~ expression ~ block ~ (KEYWORD_ELSE ~ block)? }
for_statement = { KEYWORD_FOR ~ expression ~ block }
while_statement = { KEYWORD_WHILE ~ expression ~ block }
function_def = { KEYWORD_DEF ~ (dunder_ident | ident) ~ (ParramsList | arg_list) ~ block }
block = { "{" ~ (statement)* ~ "}" }
class_def = { KEYWORD_CLASS ~ ident ~ block }

basic_statement = _{
    assignment_statement |
    print_statement |
    return_statement |
    function_call |
    function_call_stmt
}

compound_statement = _{
    if_statement |
    for_statement |
    while_statement |
    function_def |
    class_def
}

statement = {
    basic_statement |
    compound_statement
}

program = { SOI ~ (statement)* ~ EOI }